name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  setup:
    runs-on: ubuntu-22.04
    outputs:
      node-version: ${{ steps.set-version.outputs.node-version }}
    strategy:
      matrix:
        node-version: [20]
    steps:
      - name: Set matrix node version
        id: set-version
        run: echo "node-version=${{ matrix.node-version }}" >> $GITHUB_OUTPUT

  lint:
    needs: setup
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        with:
          version: 10.12.4

      - uses: actions/setup-node@v4
        with:
          node-version: ${{ needs.setup.outputs.node-version }}
          cache: 'pnpm'

      - run: pnpm install --frozen-lockfile
      - run: pnpm exec turbo run lint --filter=.

  test:
    needs: setup
    runs-on: ubuntu-22.04
    outputs:
      coverage-file: ${{ steps.set-coverage.outputs.coverage-file }}
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        with:
          version: 10.12.4

      - uses: actions/setup-node@v4
        with:
          node-version: ${{ needs.setup.outputs.node-version }}
          cache: 'pnpm'

      - run: pnpm install --frozen-lockfile
      - run: pnpm --filter=tiktok-shop-sdk test

      - name: Set coverage output
        id: set-coverage
        run: echo "coverage-file=./packages/sdk/coverage/lcov.info" >> $GITHUB_OUTPUT

  build:
    needs: [lint, test]
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        with:
          version: 10.12.4

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - run: pnpm install --frozen-lockfile
      - run: pnpm exec turbo run build --dry

  codecov:
    name: Upload to Codecov
    needs: test
    runs-on: ubuntu-22.04
    if: ${{ !cancelled() }}
    steps:
      - uses: actions/checkout@v4

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./packages/sdk/coverage/lcov.info
